### ISSUE TITLE
Attach to PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [Saransh-cpp/PyHEP22-Constructing-HEP-vectors-and-analyzing-HEP-data-using-Vector#5]
Hi @Saransh-cpp,

I noticed that you already minted a DOI for your talk/repository (BTW, the one given on the README does not apppear to be the most recent one). That's great. I then just need that you attach the Zenodo entry to the pyhep2022 community (I will get a ping to curate from Zenodo) ... Can you do that?

While at it you can also update the title (the auto-generated one is ugly) and the conference related metadata "Meeting" as at for example https://zenodo.org/record/7075511#.YyyKdXZBxPY?

Many thanks,
Eduardo

**Comment by Saransh-cpp** [comment]
@eduardo-rodrigues thanks for the information! Could you please check now? I have updated the badge as well as the zenodo data.

**Comment by Saransh-cpp** [comment]
(please re-open if anything else is required, checking this off from my TODO list 😅)

**Comment by eduardo-rodrigues** [comment]
All fine, thanks.
